-- -----------------------------------------------------
-- Table AP_APP
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_APP(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(45) NOT NULL,
  DESCRIPTION CLOB NULL,
  TYPE VARCHAR(200) NOT NULL,
  TENANT_ID VARCHAR(45) NOT NULL,
  STATUS VARCHAR(45) NOT NULL DEFAULT 'ACTIVE',
  SUB_TYPE VARCHAR(45) NOT NULL,
  CURRENCY VARCHAR(45) NULL DEFAULT '$',
  RATING INT(11) NULL,
  DEVICE_TYPE_ID INT NOT NULL,
  PRIMARY KEY (ID)
);

-- -----------------------------------------------------
-- Table AP_APP_RELEASE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_APP_RELEASE(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  DESCRIPTION CLOB NOT NULL,
  VERSION VARCHAR(10) NOT NULL,
  TENANT_ID VARCHAR(45) NOT NULL,
  UUID VARCHAR(200) NOT NULL,
  RELEASE_TYPE VARCHAR(45) NOT NULL,
  PACKAGE_NAME VARCHAR(45) NOT NULL,
  APP_PRICE decimal(6, 2) NULL DEFAULT NULL,
  INSTALLER_LOCATION VARCHAR(100) NOT NULL,
  ICON_LOCATION VARCHAR(100) NOT NULL,
  BANNER_LOCATION VARCHAR(100) NOT NULL,
  SC_1_LOCATION VARCHAR(100) NOT NULL,
  SC_2_LOCATION VARCHAR(100) NULL DEFAULT NULL,
  SC_3_LOCATION VARCHAR(100) NULL DEFAULT NULL,
  APP_HASH_VALUE VARCHAR(1000) NOT NULL,
  SHARED_WITH_ALL_TENANTS tinyINT NOT NULL,
  APP_META_INFO CLOB NULL DEFAULT NULL,
  SUPPORTED_OS_VERSIONS VARCHAR(45) NOT NULL,
  RATING DOUBLE NULL DEFAULT NULL,
  CURRENT_STATE VARCHAR(45) NOT NULL,
  RATED_USERS INT(11) NULL,
  AP_APP_ID INT(11) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_AP_APP_RELEASE_AP_APP1
    FOREIGN KEY (AP_APP_ID)
      REFERENCES AP_APP (ID));

-- -----------------------------------------------------
-- Table AP_APP_REVIEW
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_APP_REVIEW(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TENANT_ID VARCHAR(45) NOT NULL,
  COMMENT VARCHAR(250) NOT NULL,
  REPLY_COMMENT VARCHAR(250) NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  RATING INT(11) NULL,
  USERNAME VARCHAR(45) NOT NULL,
  AP_APP_RELEASE_ID INT NOT NULL,
  AP_APP_ID INT(11) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_AP_APP_COMMENT_AP_APP_RELEASE1
    FOREIGN KEY (
      AP_APP_RELEASE_ID,
      AP_APP_ID
    )
    REFERENCES AP_APP_RELEASE (
      ID,
      AP_APP_ID
    ) );

-- -----------------------------------------------------
-- Table AP_APP_LIFECYCLE_STATE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_APP_LIFECYCLE_STATE(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  CURRENT_STATE VARCHAR(45) NOT NULL,
  PREVIOUS_STATE VARCHAR(45) NOT NULL,
  TENANT_ID VARCHAR(45) NOT NULL,
  UPDATED_BY VARCHAR(100) NOT NULL,
  UPDATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  AP_APP_RELEASE_ID INT NOT NULL,
  AP_APP_ID INT(11) NOT NULL,
  PRIMARY KEY (
    ID,
    AP_APP_RELEASE_ID,
    AP_APP_ID
  ),
  CONSTRAINT fk_AP_APP_LIFECYCLE_STATE_AP_APP_RELEASE1
    FOREIGN KEY (
      AP_APP_RELEASE_ID,
      AP_APP_ID
    )
    REFERENCES AP_APP_RELEASE (
      ID,
      AP_APP_ID
    ) );

-- -----------------------------------------------------
-- Table AP_APP_TAG
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_APP_TAG(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TENANT_ID VARCHAR(45) NOT NULL,
  TAG VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID)
);

-- -----------------------------------------------------
-- Table AP_DEVICE_SUBSCRIPTION
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_DEVICE_SUBSCRIPTION(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TENANT_ID VARCHAR(45) NOT NULL,
  SUBSCRIBED_BY VARCHAR(100) NOT NULL,
  SUBSCRIBED_TIMESTAMP timestamp NOT NULL,
  UNSUBSCRIBED INT(11) NULL DEFAULT NULL,
  UNSUBSCRIBED_BY INT(11) NULL DEFAULT NULL,
  UNSUBSCRIBED_TIMESTAMP timestamp NULL DEFAULT NULL,
  SUBSCRIBED_FROM VARCHAR(45) NULL,
  DM_DEVICE_ID INT(11) NOT NULL,
  AP_APP_RELEASE_ID INT(11) NOT NULL,
  AP_APP_ID INT(11) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_AP_DEVICE_SUBSCRIPTION_AP_APP_RELEASE1
    FOREIGN KEY (
      AP_APP_RELEASE_ID,
      AP_APP_ID
    )
    REFERENCES AP_APP_RELEASE (
      ID,
      AP_APP_ID
    ) );

-- -----------------------------------------------------
-- Table AP_GROUP_SUBSCRIPTION
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_GROUP_SUBSCRIPTION(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TENANT_ID VARCHAR(45) NOT NULL,
  SUBSCRIBED_BY VARCHAR(100) NOT NULL,
  SUBSCRIBED_TIMESTAMP timestamp NOT NULL,
  UNSUBSCRIBED INT(11) NULL DEFAULT NULL,
  UNSUBSCRIBED_BY INT(11) NULL DEFAULT NULL,
  UNSUBSCRIBED_TIMESTAMP timestamp NULL DEFAULT NULL,
  DM_GROUP_ID INT(11) NOT NULL,
  AP_APP_RELEASE_ID INT(11) NOT NULL,
  AP_APP_ID INT(11) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_AP_GROUP_SUBSCRIPTION_AP_APP_RELEASE1
    FOREIGN KEY (
      AP_APP_RELEASE_ID,
      AP_APP_ID
    )
    REFERENCES AP_APP_RELEASE (
      ID,
      AP_APP_ID
    ) );

-- -----------------------------------------------------
-- Table AP_ROLE_SUBSCRIPTION
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_ROLE_SUBSCRIPTION(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TENANT_ID VARCHAR(45) NOT NULL,
  ROLE_NAME VARCHAR(100) NOT NULL,
  SUBSCRIBED_BY VARCHAR(100) NOT NULL,
  SUBSCRIBED_TIMESTAMP timestamp NOT NULL,
  UNSUBSCRIBED INT(11) NULL DEFAULT NULL,
  UNSUBSCRIBED_BY INT(11) NULL DEFAULT NULL,
  UNSUBSCRIBED_TIMESTAMP timestamp NULL DEFAULT NULL,
  AP_APP_RELEASE_ID INT(11) NOT NULL,
  AP_APP_ID INT(11) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_AP_ROLE_SUBSCRIPTION_AP_APP_RELEASE1
    FOREIGN KEY (
      AP_APP_RELEASE_ID,
      AP_APP_ID
    )
    REFERENCES AP_APP_RELEASE (
      ID,
      AP_APP_ID
    ) );

-- -----------------------------------------------------
-- Table AP_UNRESTRICTED_ROLE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_UNRESTRICTED_ROLE(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TENANT_ID VARCHAR(45) NOT NULL,
  ROLE VARCHAR(45) NOT NULL,
  AP_APP_ID INT(11) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_AP_APP_VISIBILITY_AP_APP1
    FOREIGN KEY (AP_APP_ID)
    REFERENCES AP_APP (ID) );

-- -----------------------------------------------------
-- Table AP_USER_SUBSCRIPTION
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_USER_SUBSCRIPTION(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TENANT_ID VARCHAR(45) NOT NULL,
  USER_NAME VARCHAR(100) NOT NULL,
  SUBSCRIBED_BY VARCHAR(100) NOT NULL,
  SUBSCRIBED_TIMESTAMP timestamp NOT NULL,
  UNSUBSCRIBED INT(11) NULL DEFAULT NULL,
  UNSUBSCRIBED_BY INT(11) NULL DEFAULT NULL,
  UNSUBSCRIBED_TIMESTAMP timestamp NULL DEFAULT NULL,
  AP_APP_RELEASE_ID INT(11) NOT NULL,
  AP_APP_ID INT(11) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_AP_USER_SUBSCRIPTION_AP_APP_RELEASE1
    FOREIGN KEY (
      AP_APP_RELEASE_ID,
      AP_APP_ID
    )
    REFERENCES AP_APP_RELEASE (
      ID,
      AP_APP_ID
    ) );

-- -----------------------------------------------------
-- Table AP_APP_CATEGORY
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_APP_CATEGORY(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TENANT_ID VARCHAR(45) NOT NULL,
  CATEGORY VARCHAR(45) NOT NULL,
  CATEGORY_ICON VARCHAR(45) NULL,
  PRIMARY KEY (ID)
);

-- -----------------------------------------------------
-- Table AP_APP_TAG_MAPPING
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_APP_TAG_MAPPING(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  AP_APP_TAG_ID INT(11) NOT NULL,
  AP_APP_ID INT(11) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_AP_APP_TAG_copy1_AP_APP_TAG1
    FOREIGN KEY (AP_APP_TAG_ID)
    REFERENCES AP_APP_TAG (ID),
  CONSTRAINT fk_AP_APP_TAG_copy1_AP_APP1
    FOREIGN KEY (AP_APP_ID)
    REFERENCES AP_APP (ID) );

-- -----------------------------------------------------
-- Table AP_APP_CATEGORY_MAPPING
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AP_APP_CATEGORY_MAPPING(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  AP_APP_CATEGORY_ID INT(11) NOT NULL,
  AP_APP_ID INT(11) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_AP_APP_CATEGORY_copy1_AP_APP_CATEGORY1
    FOREIGN KEY (AP_APP_CATEGORY_ID)
    REFERENCES AP_APP_CATEGORY (ID),
  CONSTRAINT fk_AP_APP_CATEGORY_copy1_AP_APP1
    FOREIGN KEY (AP_APP_ID)
    REFERENCES AP_APP (ID) );
