-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_APP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_APP`
(
  `ID`             INT(11)      NOT NULL,
  `NAME`           VARCHAR(45)  NOT NULL,
  `DESCRIPTION`    TEXT         NULL,
  `TYPE`           VARCHAR(200) NOT NULL,
  `TENANT_ID`      INT(11)      NOT NULL,
  `STATUS`         VARCHAR(45)  NOT NULL DEFAULT 'ACTIVE ',
  `SUB_TYPE`       VARCHAR(45)  NOT NULL,
  `CURRENCY`       VARCHAR(45)  NULL     DEFAULT '$',
  `RATING`         INT(11)      NULL,
  `DEVICE_TYPE_ID` INT(11)      NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_APP_RELEASE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_APP_RELEASE`
(
  `ID`                      INT(11)       NOT NULL,
  `DESCRIPTION`             TEXT          NOT NULL,
  `VERSION`                 VARCHAR(20)   NOT NULL,
  `TENANT_ID`               INT(11)       NOT NULL,
  `UUID`                    VARCHAR(200)  NOT NULL,
  `RELEASE_TYPE`            VARCHAR(45)   NOT NULL,
  `APP_PRICE`               DECIMAL(6, 2) NULL DEFAULT NULL,
  `STORED_LOCATION`         VARCHAR(45)   NOT NULL,
  `BANNER_LOCATION`         VARCHAR(45)   NOT NULL,
  `SC_1_LOCATION`           VARCHAR(45)   NOT NULL,
  `SC_2_LOCATION`           VARCHAR(45)   NULL DEFAULT NULL,
  `SC_3_LOCATION`           VARCHAR(45)   NULL DEFAULT NULL,
  `APP_HASH_VALUE`          VARCHAR(1000) NOT NULL,
  `SHARED_WITH_ALL_TENANTS` TINYINT(1)    NULL DEFAULT NULL,
  `APP_META_INFO`           TEXT          NULL DEFAULT NULL,
  `PACKAGE_NAME`            VARCHAR(45)   NOT NULL,
  `SUPPORTED_OS_VERSIONS`   VARCHAR(45)   NULL,
  `RATING`                  DOUBLE        NULL DEFAULT NULL,
  `CURRENT_STATE`           VARCHAR(45)   NULL,
  `RATED_USERS`             INT(11)       NULL,
  `AP_APP_ID`               INT(11)       NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_RELEASE_AP_APP1_idx` (`AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_APP_RELEASE_AP_APP1`
    FOREIGN KEY (`AP_APP_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_APP_REVIEW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_APP_REVIEW`
(
  `ID`                  INT(11)      NOT NULL,
  `TENANT_ID`           INT(11)      NOT NULL,
  `COMMENT`             TEXT NOT NULL,
  `ROOT_PARENT_ID`      INT(11)      NOT NULL,
  `IMMEDIATE_PARENT_ID` INT(11) NOT NULL,
  `CREATED_AT`          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_AT`         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `RATING`              INT(11)      NOT NULL,
  `USERNAME`            VARCHAR(45)  NOT NULL,
  `AP_APP_RELEASE_ID`   INT(11)      NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_REVIEW_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC),
  CONSTRAINT `fk_AP_APP_REVIEW_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP_RELEASE` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_APP_LIFECYCLE_STATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_APP_LIFECYCLE_STATE`
(
  `ID`                INT(11)      NOT NULL,
  `CURRENT_STATE`     VARCHAR(45)  NOT NULL,
  `PREVIOUS_STATE`    VARCHAR(45)  NOT NULL,
  `TENANT_ID`         INT(11)      NOT NULL,
  `UPDATED_BY`        VARCHAR(100) NOT NULL,
  `UPDATED_AT`        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `REASON`            VARCHAR(45)  NULL,
  `AP_APP_RELEASE_ID` INT(11)      NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_LIFECYCLE_STATE_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC),
  CONSTRAINT `fk_AP_APP_LIFECYCLE_STATE_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP_RELEASE` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_APP_TAG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_APP_TAG`
(
  `ID`        INT(11)      NOT NULL,
  `TAG`       VARCHAR(100) NOT NULL,
  `TENANT_ID` INT(11)      NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_DEVICE_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_DEVICE_SUBSCRIPTION`
(
  `ID`                     INT(11)      NOT NULL,
  `TENANT_ID`              INT(11)      NOT NULL,
  `SUBSCRIBED_BY`          VARCHAR(100) NOT NULL,
  `SUBSCRIBED_TIMESTAMP`   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UNSUBSCRIBED`           TINYINT(1)   NULL     DEFAULT NULL,
  `UNSUBSCRIBED_BY`        VARCHAR(100) NULL     DEFAULT NULL,
  `UNSUBSCRIBED_TIMESTAMP` TIMESTAMP    NULL     DEFAULT NULL,
  `ACTION_TRIGGERED_FROM`        VARCHAR(45)  NULL,
  `DM_DEVICE_ID`           INT(11)      NOT NULL,
  `AP_APP_RELEASE_ID`      INT(11)      NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_DEVICE_SUBSCRIPTION_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC),
  CONSTRAINT `fk_AP_DEVICE_SUBSCRIPTION_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP_RELEASE` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_GROUP_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_GROUP_SUBSCRIPTION`
(
  `ID`                     INT(11)      NOT NULL,
  `TENANT_ID`              INT(11)      NOT NULL,
  `SUBSCRIBED_BY`          VARCHAR(100) NOT NULL,
  `SUBSCRIBED_TIMESTAMP`   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UNSUBSCRIBED`           TINYINT(1)   NULL     DEFAULT NULL,
  `UNSUBSCRIBED_BY`        VARCHAR(100) NULL     DEFAULT NULL,
  `UNSUBSCRIBED_TIMESTAMP` TIMESTAMP    NULL     DEFAULT NULL,
  `GROUP_NAME`             VARCHAR(100)      NOT NULL,
  `AP_APP_RELEASE_ID`      INT(11)      NOT NULL,
  INDEX `fk_AP_GROUP_SUBSCRIPTION_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC),
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_AP_GROUP_SUBSCRIPTION_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP_RELEASE` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_ROLE_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_ROLE_SUBSCRIPTION`
(
  `ID`                     INT(11)      NOT NULL,
  `TENANT_ID`              INT(11)      NOT NULL,
  `ROLE_NAME`              VARCHAR(100) NOT NULL,
  `SUBSCRIBED_BY`          VARCHAR(100) NOT NULL,
  `SUBSCRIBED_TIMESTAMP`   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UNSUBSCRIBED`           TINYINT(1)   NULL     DEFAULT NULL,
  `UNSUBSCRIBED_BY`        VARCHAR(100) NULL     DEFAULT NULL,
  `UNSUBSCRIBED_TIMESTAMP` TIMESTAMP    NULL     DEFAULT NULL,
  `AP_APP_RELEASE_ID`      INT(11)      NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_ROLE_SUBSCRIPTION_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC),
  CONSTRAINT `fk_AP_ROLE_SUBSCRIPTION_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP_RELEASE` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_UNRESTRICTED_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_UNRESTRICTED_ROLE`
(
  `ID`        INT(11)      NOT NULL,
  `TENANT_ID` INT(11)      NOT NULL,
  `ROLE`      VARCHAR(100) NOT NULL,
  `AP_APP_ID` INT(11)      NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_VISIBILITY_AP_APP1_idx` (`AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_APP_VISIBILITY_AP_APP1`
    FOREIGN KEY (`AP_APP_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_USER_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_USER_SUBSCRIPTION`
(
  `ID`                     INT(11)      NOT NULL,
  `TENANT_ID`              INT(11)      NOT NULL,
  `USER_NAME`              VARCHAR(100) NOT NULL,
  `SUBSCRIBED_BY`          VARCHAR(100) NOT NULL,
  `SUBSCRIBED_TIMESTAMP`   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UNSUBSCRIBED`           TINYINT(1)   NULL     DEFAULT NULL,
  `UNSUBSCRIBED_BY`        VARCHAR(100) NULL     DEFAULT NULL,
  `UNSUBSCRIBED_TIMESTAMP` TIMESTAMP    NULL     DEFAULT NULL,
  `AP_APP_RELEASE_ID`      INT(11)      NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_USER_SUBSCRIPTION_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC),
  CONSTRAINT `fk_AP_USER_SUBSCRIPTION_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP_RELEASE` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_APP_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_APP_CATEGORY`
(
  `ID`            INT(11)     NOT NULL,
  `CATEGORY`      VARCHAR(45) NOT NULL,
  `CATEGORY_ICON` VARCHAR(45) NULL,
  `TENANT_ID`     INT(11)     NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_APP_TAG_MAPPING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_APP_TAG_MAPPING`
(
  `ID`            INT(11) NOT NULL,
  `TENANT_ID`     INT(11) NOT NULL,
  `AP_APP_TAG_ID` INT(11) NOT NULL,
  `AP_APP_ID`     INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_TAG_copy1_AP_APP_TAG1_idx` (`AP_APP_TAG_ID` ASC),
  INDEX `fk_AP_APP_TAG_copy1_AP_APP1_idx` (`AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_APP_TAG_copy1_AP_APP_TAG1`
    FOREIGN KEY (`AP_APP_TAG_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP_TAG` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_AP_APP_TAG_copy1_AP_APP1`
    FOREIGN KEY (`AP_APP_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_APP_CATEGORY_MAPPING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_APP_CATEGORY_MAPPING`
(
  `ID`                 INT(11) NOT NULL,
  `TENANT_ID`          INT(11) NOT NULL,
  `AP_APP_CATEGORY_ID` INT(11) NOT NULL,
  `AP_APP_ID`          INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_CATEGORY_copy1_AP_APP_CATEGORY1_idx` (`AP_APP_CATEGORY_ID` ASC),
  INDEX `fk_AP_APP_CATEGORY_copy1_AP_APP1_idx` (`AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_APP_CATEGORY_copy1_AP_APP_CATEGORY1`
    FOREIGN KEY (`AP_APP_CATEGORY_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP_CATEGORY` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_AP_APP_CATEGORY_copy1_AP_APP1`
    FOREIGN KEY (`AP_APP_ID`)
      REFERENCES `APP_MANAGER`.`AP_APP` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_APP_OP_DEVICE_MAPPING` (
  `ID`                          INT(11) NOT NULL AUTO_INCREMENT,
  `TENANT_ID`                   INT(11) NOT NULL,
  `OPERATION_ID`                INT(11) NOT NULL,
  `AP_DEVICE_SUBSCRIPTION_ID`   INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_OP_DEVICE_MAPPING_AP_DEVICE_SUBSCRIPTION1_idx` (`AP_DEVICE_SUBSCRIPTION_ID` ASC),
  CONSTRAINT `fk_AP_APP_OP_DEVICE_MAPPING_AP_DEVICE_SUBSCRIPTION1`
    FOREIGN KEY (`AP_DEVICE_SUBSCRIPTION_ID`)
    REFERENCES `APP_MANAGER`.`AP_DEVICE_SUBSCRIPTION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_SCHEDULED_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APP_MANAGER`.`AP_SCHEDULED_SUBSCRIPTION`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TASK_NAME` VARCHAR(100) NOT NULL,
  `APPLICATION_UUID` VARCHAR(36) NOT NULL,
  `SUBSCRIBER_LIST` TEXT NOT NULL,
  `STATUS` VARCHAR(15) NOT NULL,
  `SCHEDULED_AT` TIMESTAMP NOT NULL,
  `SCHEDULED_BY` VARCHAR(100) NOT NULL,
  `SCHEDULED_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_AP_SCHEDULED_SUBSCRIPTION_AP_APP_RELEASE`
    FOREIGN KEY (`APPLICATION_UUID`)
    REFERENCES `AP_APP_RELEASE` (`UUID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
