-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `AP_APP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_APP` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` TEXT NULL,
  `TYPE` VARCHAR(200) NOT NULL,
  `TENANT_ID` VARCHAR(45) NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL DEFAULT 'ACTIVE',
  `SUB_TYPE` VARCHAR(45) NOT NULL,
  `CURRENCY` VARCHAR(45) NULL DEFAULT '$',
  `RATING` INT(11) NULL,
  `DEVICE_TYPE_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AP_APP_RELEASE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_APP_RELEASE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` TEXT NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `TENANT_ID` VARCHAR(45) NOT NULL,
  `UUID` VARCHAR(200) NOT NULL,
  `RELEASE_TYPE` VARCHAR(45) NOT NULL,
  `PACKAGE_NAME` VARCHAR(45) NOT NULL,
  `APP_PRICE` DECIMAL(6,2) NULL DEFAULT NULL,
  `INSTALLER_LOCATION` VARCHAR(100) NOT NULL,
  `ICON_LOCATION` VARCHAR(100) NOT NULL,
  `BANNER_LOCATION` VARCHAR(100) NOT NULL,
  `SC_1_LOCATION` VARCHAR(100) NOT NULL,
  `SC_2_LOCATION` VARCHAR(100) NULL DEFAULT NULL,
  `SC_3_LOCATION` VARCHAR(100) NULL DEFAULT NULL,
  `APP_HASH_VALUE` VARCHAR(1000) NOT NULL,
  `SHARED_WITH_ALL_TENANTS` TINYINT(1) NOT NULL,
  `APP_META_INFO` TEXT NULL DEFAULT NULL,
  `SUPPORTED_OS_VERSIONS` VARCHAR(45) NOT NULL,
  `RATING` DOUBLE NULL DEFAULT NULL,
  `CURRENT_STATE` VARCHAR(45) NOT NULL,
  `RATED_USERS` INT(11) NULL,
  `AP_APP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_RELEASE_AP_APP1_idx` (`AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_APP_RELEASE_AP_APP1`
    FOREIGN KEY (`AP_APP_ID`)
    REFERENCES `AP_APP` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '																																																																																																																																																																																																																																																																																																																																																																																																																																																																		';


-- -----------------------------------------------------
-- Table `AP_APP_REVIEW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_APP_REVIEW` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TENANT_ID` VARCHAR(45) NOT NULL,
  `COMMENT` VARCHAR(250) NOT NULL,
  `REPLY_COMMENT` VARCHAR(250) NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `RATING` INT(11) NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `AP_APP_RELEASE_ID` INT(11) NOT NULL,
  `AP_APP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_COMMENT_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC, `AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_APP_COMMENT_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID` , `AP_APP_ID`)
    REFERENCES `AP_APP_RELEASE` (`ID` , `AP_APP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AP_APP_LIFECYCLE_STATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_APP_LIFECYCLE_STATE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CURRENT_STATE` VARCHAR(45) NOT NULL,
  `PREVIOUSE_STATE` VARCHAR(45) NOT NULL,
  `TENANT_ID` VARCHAR(45) NOT NULL,
  `UPDATED_BY` VARCHAR(100) NOT NULL,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `AP_APP_RELEASE_ID` INT(11) NOT NULL,
  `AP_APP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `AP_APP_RELEASE_ID`, `AP_APP_ID`),
  INDEX `fk_AP_APP_LIFECYCLE_STATE_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC, `AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_APP_LIFECYCLE_STATE_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID` , `AP_APP_ID`)
    REFERENCES `AP_APP_RELEASE` (`ID` , `AP_APP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AP_APP_TAG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_APP_TAG` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TENANT_ID` VARCHAR(45) NOT NULL,
  `TAG` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AP_DEVICE_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_DEVICE_SUBSCRIPTION` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TENANT_ID` VARCHAR(45) NOT NULL,
  `SUBSCRIBED_BY` VARCHAR(100) NOT NULL,
  `SUBSCRIBED_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UNSUBSCRIBED` INT(11) NULL DEFAULT NULL,
  `UNSUBSCRIBED_BY` INT(11) NULL DEFAULT NULL,
  `UNSUBSCRIBED_TIMESTAMP` TIMESTAMP NULL DEFAULT NULL,
  `SUBSCRIBED_FROM` VARCHAR(45) NULL,
  `DM_DEVICE_ID` INT(11) NOT NULL,
  `AP_APP_RELEASE_ID` INT(11) NOT NULL,
  `AP_APP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AM_DEVICE_SUBSCRIPTION_DM_DEVICE1_idx` (`DM_DEVICE_ID` ASC),
  INDEX `fk_AP_DEVICE_SUBSCRIPTION_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC, `AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_DEVICE_SUBSCRIPTION_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID` , `AP_APP_ID`)
    REFERENCES `AP_APP_RELEASE` (`ID` , `AP_APP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `AP_GROUP_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_GROUP_SUBSCRIPTION` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TENANT_ID` VARCHAR(45) NOT NULL,
  `SUBSCRIBED_BY` VARCHAR(100) NOT NULL,
  `SUBSCRIBED_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UNSUBSCRIBED` INT(11) NULL DEFAULT NULL,
  `UNSUBSCRIBED_BY` INT(11) NULL DEFAULT NULL,
  `UNSUBSCRIBED_TIMESTAMP` TIMESTAMP NULL DEFAULT NULL,
  `DM_GROUP_ID` INT(11) NOT NULL,
  `AP_APP_RELEASE_ID` INT(11) NOT NULL,
  `AP_APP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AM_GROUP_SUBSCRIPTION_DM_GROUP1_idx` (`DM_GROUP_ID` ASC),
  INDEX `fk_AP_GROUP_SUBSCRIPTION_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC, `AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_GROUP_SUBSCRIPTION_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID` , `AP_APP_ID`)
    REFERENCES `AP_APP_RELEASE` (`ID` , `AP_APP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `APP_MANAGER`.`AP_ROLE_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_ROLE_SUBSCRIPTION` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TENANT_ID` VARCHAR(45) NOT NULL,
  `ROLE_NAME` VARCHAR(100) NOT NULL,
  `SUBSCRIBED_BY` VARCHAR(100) NOT NULL,
  `SUBSCRIBED_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UNSUBSCRIBED` INT(11) NULL DEFAULT NULL,
  `UNSUBSCRIBED_BY` INT(11) NULL DEFAULT NULL,
  `UNSUBSCRIBED_TIMESTAMP` TIMESTAMP NULL DEFAULT NULL,
  `AP_APP_RELEASE_ID` INT(11) NOT NULL,
  `AP_APP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_ROLE_SUBSCRIPTION_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC, `AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_ROLE_SUBSCRIPTION_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID` , `AP_APP_ID`)
    REFERENCES `AP_APP_RELEASE` (`ID` , `AP_APP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AP_UNRESTRICTED_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_UNRESTRICTED_ROLE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TENANT_ID` VARCHAR(45) NOT NULL,
  `ROLE` VARCHAR(45) NOT NULL,
  `AP_APP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_VISIBILITY_AP_APP1_idx` (`AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_APP_VISIBILITY_AP_APP1`
    FOREIGN KEY (`AP_APP_ID`)
    REFERENCES `AP_APP` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AP_USER_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_USER_SUBSCRIPTION` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TENANT_ID` VARCHAR(45) NOT NULL,
  `USER_NAME` VARCHAR(100) NOT NULL,
  `SUBSCRIBED_BY` VARCHAR(100) NOT NULL,
  `SUBSCRIBED_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UNSUBSCRIBED` INT(11) NULL DEFAULT NULL,
  `UNSUBSCRIBED_BY` INT(11) NULL DEFAULT NULL,
  `UNSUBSCRIBED_TIMESTAMP` TIMESTAMP NULL DEFAULT NULL,
  `AP_APP_RELEASE_ID` INT(11) NOT NULL,
  `AP_APP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_USER_SUBSCRIPTION_AP_APP_RELEASE1_idx` (`AP_APP_RELEASE_ID` ASC, `AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_USER_SUBSCRIPTION_AP_APP_RELEASE1`
    FOREIGN KEY (`AP_APP_RELEASE_ID` , `AP_APP_ID`)
    REFERENCES `AP_APP_RELEASE` (`ID` , `AP_APP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AP_APP_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_APP_CATEGORY` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TENANT_ID` VARCHAR(45) NOT NULL,
  `CATEGORY` VARCHAR(45) NOT NULL,
  `CATEGORY_ICON` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AP_APP_TAG_MAPPING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_APP_TAG_MAPPING` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `AP_APP_TAG_ID` INT(11) NOT NULL,
  `AP_APP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_TAG_copy1_AP_APP_TAG1_idx` (`AP_APP_TAG_ID` ASC),
  INDEX `fk_AP_APP_TAG_copy1_AP_APP1_idx` (`AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_APP_TAG_copy1_AP_APP_TAG1`
    FOREIGN KEY (`AP_APP_TAG_ID`)
    REFERENCES `AP_APP_TAG` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AP_APP_TAG_copy1_AP_APP1`
    FOREIGN KEY (`AP_APP_ID`)
    REFERENCES `AP_APP` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AP_APP_CATEGORY_MAPPING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP_APP_CATEGORY_MAPPING` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `AP_APP_CATEGORY_ID` INT(11) NOT NULL,
  `AP_APP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AP_APP_CATEGORY_copy1_AP_APP_CATEGORY1_idx` (`AP_APP_CATEGORY_ID` ASC),
  INDEX `fk_AP_APP_CATEGORY_copy1_AP_APP1_idx` (`AP_APP_ID` ASC),
  CONSTRAINT `fk_AP_APP_CATEGORY_copy1_AP_APP_CATEGORY1`
    FOREIGN KEY (`AP_APP_CATEGORY_ID`)
    REFERENCES `AP_APP_CATEGORY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AP_APP_CATEGORY_copy1_AP_APP1`
    FOREIGN KEY (`AP_APP_ID`)
    REFERENCES `AP_APP` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
